### ISSUE TITLE
TypeError: object() takes no parameters

### ISSUE THREAD

**Issue by infosrabah** [laura-barluzzi/django-user-language-middleware#1]
Hi,
Got error here the trace :

```python
...
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fbd44e2c9d8>
Traceback (most recent call last):
  File "/home/rabah/anugrah-pypi-local-repository/Django-dev-2.2/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/rabah/anugrah-pypi-local-repository/Django-dev-2.2/django/core/management/commands/runserver.py", line 137, in inner_run
    handler = self.get_handler(*args, **options)
  File "/home/rabah/anugrah-pypi-local-repository/Django-dev-2.2/django/contrib/staticfiles/management/commands/runserver.py", line 27, in get_handler
    handler = super().get_handler(*args, **options)
  File "/home/rabah/anugrah-pypi-local-repository/Django-dev-2.2/django/core/management/commands/runserver.py", line 64, in get_handler
    return get_internal_wsgi_application()
  File "/home/rabah/anugrah-pypi-local-repository/Django-dev-2.2/django/core/servers/basehttp.py", line 44, in get_internal_wsgi_application
    return import_string(app_path)
  File "/home/rabah/anugrah-pypi-local-repository/Django-dev-2.2/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/home/rabah/.local/share/virtualenvs/proveho-G3NgZpUh/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/rabah/dev/proveho/proveho/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/rabah/anugrah-pypi-local-repository/Django-dev-2.2/django/core/wsgi.py", line 13, in get_wsgi_application
    return WSGIHandler()
  File "/home/rabah/anugrah-pypi-local-repository/Django-dev-2.2/django/core/handlers/wsgi.py", line 135, in __init__
    self.load_middleware()
  File "/home/rabah/anugrah-pypi-local-repository/Django-dev-2.2/django/core/handlers/base.py", line 37, in load_middleware
    mw_instance = middleware(handler)
TypeError: object() takes no parameters
```

Any ideas ?

**Comment by laura-barluzzi** [comment]
Hi @infosrabah, thanks for opening this issue. I really appreciate. Could you please confirm the version of Django that you are using and the name of the list of middlewares in your `settings.py` file? e.g. you use `MIDDLEWARE` or `MIDDLEWARE_CLASSES`? Cheers

**Comment by infosrabah** [comment]
Hi @laura-barluzzi

1 - Django version is 2.2dev, 
2 - Middleware , here's the list.
```python
MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.locale.LocaleMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
```

I believe It shows the same error, when used Django 2.1,

PS: I have special raisons/requirements why I'm using Django2.2dev.

Thank you so much

**Comment by laura-barluzzi** [comment]
I don't seem to find my custom middleware in the list of your `MIDDLEWARE`; could you please revisit and retry following all the steps in the README file under the[ Usage section](https://github.com/laura-barluzzi/django-user-language-middleware/blob/master/README.rst#usage)?
Make sure to install and add `user_language_middleware.UserLanguageMiddleware` so that your `MIDDLEWARE` should look like this:
```
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'user_language_middleware.UserLanguageMiddleware',
]
```
Please let me know if this fixes the issues.

**Comment by laura-barluzzi** [comment]
@infosrabah I added a Travis check for Django 2.1 and it passes. This means that it's compatible so I believe the issue is related to the missing custom middleware in your `MIDDLEWARE` list. Please, let me know if by adding the middleware the error is fixed so I can close this issue.

**Comment by infosrabah** [comment]
Hi @laura-barluzzi,

sorry for the late respond..

the middleware that I gave you above was like before, I mean I thought you said you just want to have a look at my middleware to see if ( or [ anyway ....


here's my middleware, I made it from scratch , I mean a new project : 
```python
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'user_language_middleware.UserLanguageMiddleware',
]
```

and here's is my log after a $python3 manage.py runserver : 
```python
System check identified no issues (0 silenced).
October 15, 2018 - 12:50:39
Django version 2.2.dev20181005132628, using settings 'rado.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f2779094730>
Traceback (most recent call last):
  File "/home/rabah/anugrah-pypi-local-repository/Django-dev-2.2/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/rabah/anugrah-pypi-local-repository/Django-dev-2.2/django/core/management/commands/runserver.py", line 137, in inner_run
    handler = self.get_handler(*args, **options)
  File "/home/rabah/anugrah-pypi-local-repository/Django-dev-2.2/django/contrib/staticfiles/management/commands/runserver.py", line 27, in get_handler
    handler = super().get_handler(*args, **options)
  File "/home/rabah/anugrah-pypi-local-repository/Django-dev-2.2/django/core/management/commands/runserver.py", line 64, in get_handler
    return get_internal_wsgi_application()
  File "/home/rabah/anugrah-pypi-local-repository/Django-dev-2.2/django/core/servers/basehttp.py", line 44, in get_internal_wsgi_application
    return import_string(app_path)
  File "/home/rabah/anugrah-pypi-local-repository/Django-dev-2.2/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/home/rabah/.local/share/virtualenvs/django-user-language-middleware-P2wEXHxa/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/rabah/dev/django-user-language-middleware/rado/rado/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/rabah/anugrah-pypi-local-repository/Django-dev-2.2/django/core/wsgi.py", line 13, in get_wsgi_application
    return WSGIHandler()
  File "/home/rabah/anugrah-pypi-local-repository/Django-dev-2.2/django/core/handlers/wsgi.py", line 135, in __init__
    self.load_middleware()
  File "/home/rabah/anugrah-pypi-local-repository/Django-dev-2.2/django/core/handlers/base.py", line 37, in load_middleware
    mw_instance = middleware(handler)
TypeError: object() takes no parameters
```
thank you.

**Comment by laura-barluzzi** [comment]
@infosrabah so a first guess is that you may be using Python 3.4. As for the [Django 2.1 documentation](https://docs.djangoproject.com/en/2.1/releases/2.1/#python-compatibility), Python 3.4 and Django 2.1 are not compatible:
> Django 2.1 supports Python 3.5, 3.6, and 3.7. Django 2.0 is the last version to support Python 3.4.

If this was not the issue, could you please:
- give me some more system information;
- show me a simplified version of your app and how you use the custom middleware?

**Comment by StuartMacKay** [comment]
I see the same problem:
```
python===3.6.5
Django==2.0
```
Middleware order:
```
MIDDLEWARE = [
    ...,
    'user_language_middleware.UserLanguageMiddleware',
    'raven.contrib.django.raven_compat.middleware.SentryResponseErrorIdMiddleware',
    'raven.contrib.django.raven_compat.middleware.Sentry404CatchMiddleware'
]
```
The problem is in django,core.handlers.base.BaseHandler load_middleware method, lines 35-40
```python
        handler = convert_exception_to_response(self._get_response)
        for middleware_path in reversed(settings.MIDDLEWARE):
            middleware = import_string(middleware_path)
            try:
                mw_instance = middleware(handler)   # <------ exception raised here
            except MiddlewareNotUsed as exc:
                ...
```
To fix it I copied the UserLanguageMiddleware into my project and added the MiddlewareMixin:
```
from django.utils import translation
from django.utils.deprecation import MiddlewareMixin


class UserLanguageMiddleware(MiddlewareMixin):
    def process_response(self, request, response):
        user = getattr(request, 'user', None)
        if not user:
            return response

        if not user.is_authenticated:
            return response

        user_language = getattr(user, 'language', None)
        if not user_language:
            return response

        current_language = translation.get_language()
        if user_language == current_language:
            return response

        translation.activate(user_language)
        request.session[translation.LANGUAGE_SESSION_KEY] = user_language

        return response
```

**Comment by laura-barluzzi** [comment]
@StuartMacKay thank you so much! I will make the change very soon. I really appreciate.

@infosrabah I let you know when I update the module on `PyPi` and hopefully your issue is fixed just by updating the module.

**Comment by StuartMacKay** [comment]
@laura-barluzzi The fix I made was only to get it working. Since the mixin is for upgrading old (pre Django 1.10) middleware so it's compatible with new style middleware you should probably take a look at https://docs.djangoproject.com/en/2.1/topics/http/middleware/ just to see if there are any issues. Perhaps dropping support for pre 1.10 Django might be a better option, depending on who is using this already.

**Comment by laura-barluzzi** [comment]
@StuartMacKay thanks for double checking but no worries - I'm aware of the fact that the middlware mixin doesn't work for Django < 1.10 (that was the reason why I didn't use it at the first place). I'm working on trying to keep all versions supported, but I will surely use the middleware mixing for 1.10+ Thanks again :+1:

**Comment by infosrabah** [comment]
Python = 3.5.3
Django = 2.2 Dev

I also used MiddlewareMixin, but I wanted to be sure that you agree about that, if any bugs or supported backwards only.

You can try to ask if any one use Dj 1.10 , If so keep the backward compatibility way, if not , well the future seems promising. after all , I don't think that there's people who still using dj 1.10 anymore.


Thank you

**Comment by laura-barluzzi** [comment]
@infosrabah I made the changes and I published them on PyPi in the version 0.0.3. Could you please try to update the package and retry? Please let me know if version 0.0.3 fixes your problem.

**Comment by laura-barluzzi** [comment]
@infosrabah Since I haven't heard back I assume the issue is fixed and I close it.

In case you have a problem with the newest version 0.0.3 please open another issue and thank you again for reporting the problem, I really appreciated :+1:

**Comment by infosrabah** [comment]
Sorry for the late reply.

Fixed yes.

Thank you so much.
