### ISSUE TITLE
AttributeError: module 'django.utils.translation' has no attribute 'LANGUAGE_SESSION_KEY'

### ISSUE THREAD

**Issue by kolyat** [laura-barluzzi/django-user-language-middleware#7]
Django 4.0

```
Traceback (most recent call last):
  File "E:\env\schoolmate2\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\env\schoolmate2\lib\site-packages\django\utils\deprecation.py", line 128, in __call__
    response = self.process_response(request, response)
  File "E:\env\schoolmate2\lib\site-packages\user_language_middleware\middleware.py", line 42, in process_response
    request.session[translation.LANGUAGE_SESSION_KEY] = user_language
AttributeError: module 'django.utils.translation' has no attribute 'LANGUAGE_SESSION_KEY'
```

This is due to [deprecation](https://django.readthedocs.io/en/stable/internals/deprecation.html#deprecation-removed-in-4-0).
> django.views.i18n.set_language() will no longer set the user language in request.session (key django.utils.translation.LANGUAGE_SESSION_KEY).

**Comment by Skrattoune** [comment]
I finally found this easy solution which is super easy to implement and works directly without need for an external middleware:
https://stackoverflow.com/a/74228535
